export enum ErrorCodeEnum {
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

    //UNICITY CONSTRAINT
    DEFAULT_ALREADY_EXISTS_ERROR = "DEFAULT_ALREADY_EXISTS_ERROR",
    EMAIL_ALREADY_EXISTS_ERROR = "EMAIL_ALREADY_EXISTS_ERROR",
    CLASSIC_ACCOUNT_ALREADY_EXISTS_ERROR = "CLASSIC_ACCOUNT_ALREADY_EXISTS_ERROR",
    OAUTH_ACCOUNT_ALREADY_EXISTS_ERROR = "OAUTH_ACCOUNT_ALREADY_EXISTS_ERROR",
    GOOGLE_ACCOUNT_ALREADY_LINK_ERROR = "GOOGLE_ACCOUNT_ALREADY_LINK_ERROR",

    //TOKEN
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_INVALID = "TOKEN_INVALID",



    //NOT FOUND
    DEFAULT_NOT_FOUND_ERROR = "DEFAULT_NOT_FOUND_ERROR",
    USER_NOT_FOUND_ERROR = "USER_NOT_FOUND_ERROR",

    //MISSING
    GOOGLE_ID_MISSING_ERROR = "GOOGLE_ID_MISSING_ERROR",
    OAUTH_ID_MISSING_ERROR = "OAUTH_ID_NOT_FOUND_ERROR",
    GOOGLE_EMAIL_MISSING_ERROR = "GOOGLE_EMAIL_MISSING_ERROR",

}
