export enum ErrorCodeEnum {
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

    //UNICITY CONSTRAINT
    DEFAULT_ALREADY_EXISTS_ERROR = "DEFAULT_ALREADY_EXISTS_ERROR",
    EMAIL_ALREADY_EXISTS_ERROR = "EMAIL_ALREADY_EXISTS_ERROR",

    //TOKEN
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_INVALID = "TOKEN_INVALID",


    //NOT FOUND
    DEFAULT_NOT_FOUND_ERROR = "DEFAULT_NOT_FOUND_ERROR",

}
