export enum DtoErrorCodeEnum {
  /********* EMAIL *********/
  EMAIL_INVALID = 'EMAIL_INVALID',
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',

  /********* PASSWORD *********/
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH = 'PASSWORD_MIN_LENGTH',
  PASSWORD_WEAK = 'PASSWORD_WEAK',

  /********* KEYWORD *********/
  KEYWORD_REQUIRED = 'KEYWORD_REQUIRED',
  KEYWORD_TOO_LONG = 'KEYWORD_TOO_LONG',
}
