export enum DtoErrorCodeEnum {
  /********* EMAIL *********/
  EMAIL_INVALID = 'EMAIL_INVALID',
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',

  /********* PASSWORD *********/
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH = 'PASSWORD_MIN_LENGTH',
  PASSWORD_WEAK = 'PASSWORD_WEAK',
}
