export enum ErrorCodeEnum {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  //UNICITY CONSTRAINT
  DEFAULT_ALREADY_EXISTS_ERROR = 'DEFAULT_ALREADY_EXISTS_ERROR',
  EMAIL_ALREADY_EXISTS_ERROR = 'EMAIL_ALREADY_EXISTS_ERROR',
  CLASSIC_ACCOUNT_ALREADY_EXISTS_ERROR = 'CLASSIC_ACCOUNT_ALREADY_EXISTS_ERROR',
  OAUTH_ACCOUNT_ALREADY_EXISTS_ERROR = 'OAUTH_ACCOUNT_ALREADY_EXISTS_ERROR',
  GOOGLE_ACCOUNT_ALREADY_LINK_ERROR = 'GOOGLE_ACCOUNT_ALREADY_LINK_ERROR',

  //TOKEN
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  //NOT FOUND
  DEFAULT_NOT_FOUND_ERROR = 'DEFAULT_NOT_FOUND_ERROR',
  USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR',
  APPLICATION_NOT_FOUND_ERROR = 'APPLICATION_NOT_FOUND_ERROR',
  CONTACT_NOT_FOUND_ERROR = 'CONTACT_NOT_FOUND_ERROR',
  SKILL_NOT_FOUND_ERROR = 'SKILL_NOT_FOUND_ERROR',
  NOTE_NOT_FOUND_ERROR = 'NOTE_NOT_FOUND_ERROR',
  TODO_NOT_FOUND_ERROR = 'TODO_NOT_FOUND_ERROR',
  APPLICATION_HISTORY_NOT_FOUND_ERROR = 'APPLICATION_HISTORY_NOT_FOUND_ERROR',

  //OAUTH
  GITHUB_COMPLETED_OAUTH_FAILED = 'GITHUB_COMPLETED_OAUTH_FAILED',
  GOOGLE_COMPLETED_OAUTH_FAILED = 'GOOGLE_COMPLETED_OAUTH_FAILED',
  OAUTH_LOGIN_FAILED = 'OAUTH_LOGIN_FAILED',

  //AUTH
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_PENDING = 'ACCOUNT_PENDING',
  USER_BANNED = 'USER_BANNED',
  ACCOUNT_ALREADY_CONFIRM = 'ACCOUNT_ALREADY_CONFIRM',

  //DELETE CONFLICT
  CONTACT_DELETE_CONFLICT = 'CONTACT_DELETE_CONFLICT',
  SKILL_UPDATE_CONFLICT = 'SKILL_UPDATE_CONFLICT',
  SKILL_DELETE_CONFLICT = 'SKILL_DELETE_CONFLICT',

  //SCRAPER
  SCRAPER_EXTRACTION_FAILED_ERROR = 'SCRAPER_EXTRACTION_FAILED_ERROR',
  SCRAPER_URL_TOO_LONG = 'SCRAPER_URL_TOO_LONG',
  SCRAPER_URL_INVALID = 'SCRAPER_URL_INVALID',
  SCRAPER_URL_DOMAIN_NOT_SUPPORTED = 'SCRAPER_URL_DOMAIN_NOT_SUPPORTED',

  //LLM
  LLM_STRUCTURING_FAILED_ERROR = 'LLM_STRUCTURING_FAILED_ERROR',
  LLM_FETCH_AND_MAP_FAILED_ERROR = 'LLM_FETCH_AND_MAP_FAILED_ERROR',
}
